-- migration: fix employee number generation safety
-- purpose: prevent onboarding failures caused by invalid employee_number formats generated by sample data.
-- details:
--   * redefine public.generate_employee_number to ignore malformed suffixes by extracting digits with regex.
--   * rely on security invoker and empty search_path per project guidelines.

create or replace function public.generate_employee_number()
returns text
language plpgsql
security invoker
set search_path = ''
as $$
declare
  year_part text;
  sequence_num integer;
begin
  year_part := extract(year from current_date)::text;

  with suffixes as (
    select match[1] as suffix
    from public.employees e
    cross join lateral regexp_matches(e.employee_number, '(\d+)$') as match
    where e.employee_number is not null
      and e.employee_number like 'EMP-' || year_part || '-%'
  )
  select coalesce(max((suffix)::integer), 0) + 1
  into sequence_num
  from suffixes;

  if sequence_num is null then
    sequence_num := 1;
  end if;

  return 'EMP-' || year_part || '-' || lpad(sequence_num::text, 4, '0');
end;
$$;

