import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  // Make Dashboard the index (landing page)
  index("routes/dashboard.tsx"),
  route("/login", "routes/login.tsx"),
  route("/register", "routes/register.tsx"),
  route("/reset-password", "routes/reset-password.tsx"),
  route("/onboarding", "routes/onboarding.tsx"),
  route("/settings", "routes/settings.tsx"),
  route("/members", "routes/members.tsx"),
  route("/my-team", "routes/my-team.tsx"),
  route("/my-team/check-ins/:checkInId", "routes/my-team.check-ins.$checkInId.tsx"),
  route("/calendar", "routes/team-calendar.tsx"),
  route("/chat", "routes/chat.tsx"),
  route("/profile", "routes/profile.tsx"),
  route("/approvals", "routes/approvals.tsx"),
  route("/workflows", "routes/workflows.tsx"),
  route("/news", "routes/news.tsx"),
  route("/tasks", "routes/tasks.tsx"),
  route("/workflows/:workflowId/builder", "routes/workflows.$workflowId.builder.tsx"),
  route("/journeys/:shareToken", "routes/journeys.$shareToken.tsx"),
  route("/admin/features", "routes/admin.features.tsx"),
  route("/departments", "routes/departments.tsx"),
  route("/office-locations", "routes/office-locations.tsx"),
  route("/teams", "routes/teams.tsx"),
  route("/org-structure", "routes/org-structure.tsx"),
  route("/employees", "routes/employees.tsx"),
  route("/employees/:employeeId", "routes/employees.$employeeId.tsx"),
  route("/employees/:employeeId/growth", "routes/employees.$employeeId.growth.tsx"),
  // Time & Attendance routes
  route("/time/entries", "routes/time.entries.tsx"),
  route("/time/approvals", "routes/time.approvals.tsx"),
  route("/time/overtime", "routes/time.overtime.tsx"),
  // Leave & Absence routes
  route("/leave/requests", "routes/leave.requests.tsx"),
  route("/leave/approvals", "routes/leave.approvals.tsx"),
  route("/leave/team-calendar", "routes/leave.team-calendar.tsx"),
  route("/leave/admin", "routes/leave.admin.tsx"),
  route("/leave/reports", "routes/leave.reports.tsx"),
  // Recruiting & ATS routes
  route("/recruiting/jobs", "routes/recruiting.jobs.tsx"),
  route("/recruiting/jobs/new", "routes/recruiting.jobs.new.tsx"),
  route("/recruiting/jobs/:jobId", "routes/recruiting.jobs.$jobId.tsx"),
  route("/recruiting/jobs/:jobId/pipeline", "routes/recruiting.jobs.$jobId.pipeline.tsx"),
  route("/recruiting/candidates/:candidateId", "routes/recruiting.candidates.$candidateId.tsx"),
  route("/recruiting/analytics", "routes/recruiting.analytics.tsx"),
] satisfies RouteConfig;
